-- Task 2 Create database by Adonay Tesfamichael
DROP DATABASE IF EXISTS HR_AT;
CREATE DATABASE IF NOT EXISTS HR_AT;
USE HR_AT;
SHOW DATABASES;

-- Task 3 Create table by Adonay Tesfamichael
SHOW TABLES;
CREATE TABLE EMPLOYEE_AT(
CODE_AT INT PRIMARY KEY NOT NULL,
FIRST_NAME_AT VARCHAR(15) NOT NULL,
MIDDLE_NAME_AT VARCHAR(15) NULL,
LAST_NAME_AT VARCHAR(15) NOT NULL,
PHONE_AT CHAR(12) NOT NULL
);
SHOW TABLES;
DESCRIBE EMPLOYEE_AT;
-- Task 4 Add data by Adonay Tesfamichael 
INSERT INTO EMPLOYEE_AT VALUES
(235, 'Joe', 'Peter', 'Doe', '981-882-6813'),
(239, 'Mary', '', 'Doe', '981-083-8913'),
(240, 'Kat', 'P', 'Delto', '981-083-8914'),
(241, 'Mike', '', 'Stay', '981-083-8915'),
(242, 'Bill', 'Frank', 'Tomas', '981-083-8916');
SELECT * FROM EMPLOYEE_AT;
-- Task 5 Query the data by Adonay Tesfamichael
SELECT FIRST_NAME_AT, LAST_NAME_AT, PHONE_AT FROM EMPLOYEE_AT;
SELECT * FROM EMPLOYEE_AT WHERE LAST_NAME_AT = 'Doe';