-- Task 2 - Create database ADONAY TESFAMICHAEL
DROP DATABASE IF EXISTS HAPPY_LEARNING_AT;
CREATE DATABASE IF NOT EXISTS HAPPY_LEARNING_AT;
USE HAPPY_LEARNING_AT;
SHOW DATABASES;

-- Task 3 - Create tables ADONAY TESFAMICHAEL
CREATE TABLE TEACHER_AT(
ID_AT INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
FIRST_NAME_AT VARCHAR(15) NOT NULL,
MIDDLE_NAME_AT VARCHAR(15),
LAST_NAME_AT VARCHAR(15) NOT NULL,
HOME_PHONE_AT CHAR(13) NOT NULL,
WORK_EMAIL_AT VARCHAR(30) NOT NULL,
PERSONAL_EMAIL_AT VARCHAR(30),
COLLEGE_AT VARCHAR(50),
HIGHEST_DEGREE_AT VARCHAR(5) NOT NULL,
DEGREE_AREA_AT VARCHAR(25) NOT NULL
);
DESCRIBE TEACHER_AT;

CREATE TABLE CLASS_AT(
CODE_AT VARCHAR(2) PRIMARY KEY NOT NULL,
AGE_LEVEL_AT VARCHAR(7) NOT NULL,
COLOR_AT VARCHAR(5) NOT NULL,
ROOM_NUMBER_AT INT NOT NULL,
PHONE_NUMBER_AT CHAR(13) NOT NULL,
DIRECTION_AT VARCHAR(160),
CAPACITY_AT INT NOT NULL
);
DESCRIBE CLASS_AT;

CREATE TABLE ASSIGNMENT_AT(
CLASS_AT_CODE_AT VARCHAR(2) NOT NULL, 
TEACHER_AT_ID_AT INT NOT NULL,
FOREIGN KEY (CLASS_AT_CODE_AT) REFERENCES CLASS_AT(CODE_AT),
FOREIGN KEY (TEACHER_AT_ID_AT) REFERENCES TEACHER_AT(ID_AT)
);
DESCRIBE ASSIGNMENT_AT;

CREATE TABLE STUDENT_AT(
ID_AT INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
FIRST_NAME_AT VARCHAR(15) NOT NULL,
MIDDLE_NAME_AT VARCHAR(15),
LAST_NAME_AT VARCHAR(15) NOT NULL,
NICK_NAME_AT VARCHAR(10),
DATE_OF_BIRTH_AT DATE NOT NULL,
ADDRESS_AT VARCHAR(55) NOT NULL,
CITY_AT VARCHAR(15) NOT NULL,
ZIPCODE_AT DECIMAL(5,0) NOT NULL,
STREET_AT VARCHAR(35) NOT NULL,
CLASS_AT_CODE_AT VARCHAR(2) NOT NULL,
FOREIGN KEY (CLASS_AT_CODE_AT) REFERENCES CLASS_AT(CODE_AT)
);
DESCRIBE STUDENT_AT;

CREATE TABLE PARENT_AT(
ID_AT INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
FIRST_NAME_AT VARCHAR(15) NOT NULL,
MIDDLE_NAME_AT VARCHAR(15),
LAST_NAME_AT VARCHAR(15) NOT NULL,
HOME_PHONE_AT CHAR(13),
MOBILE_PHONE_AT CHAR(13) NOT NULL,
WORK_PHONE_AT CHAR(13),
EMAIL_AT VARCHAR(30),
RELATION VARCHAR(20) NOT NULL
);
DESCRIBE PARENT_AT;

CREATE TABLE RELATIONSHIP_AT(
STUDENT_AT_ID_AT INT NOT NULL,
PARENT_AT_ID_AT INT NOT NULL,
FOREIGN KEY (STUDENT_AT_ID_AT) REFERENCES STUDENT_AT(ID_AT),
FOREIGN KEY (PARENT_AT_ID_AT) REFERENCES PARENT_AT(ID_AT)
);
DESCRIBE RELATIONSHIP_AT;

CREATE TABLE LUNCH_ORDER_AT(
ID_AT INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
QUANTITY_AT INT NOT NULL,
DATE_AT DATE NOT NULL,
STUDENT_AT_ID_AT INT NOT NULL,
FOREIGN KEY (STUDENT_AT_ID_AT) REFERENCES STUDENT_AT(ID_AT)
);
DESCRIBE LUNCH_ORDER_AT;

CREATE TABLE LUNCH_ITEM_AT(
CODE_AT INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
ITEM_NAME_AT VARCHAR(26) NOT NULL,
CALORIES INT NOT NULL
);
DESCRIBE LUNCH_ITEM_AT;

CREATE TABLE ORDER_ITEM_AT(
LUNCH_ORDER_AT_ID_AT INT NOT NULL,
LUNCH_ITEM_AT_CODE_AT INT NOT NULL,
FOREIGN KEY (LUNCH_ORDER_AT_ID_AT) REFERENCES LUNCH_ORDER_AT(ID_AT),
FOREIGN KEY (LUNCH_ITEM_AT_CODE_AT) REFERENCES LUNCH_ITEM_AT(CODE_AT)
);
DESCRIBE ORDER_ITEM_AT;

-- Task 4 - Add data ADONAY TESFAMICHAEL
INSERT INTO TEACHER_AT VALUES
(1,'Katheryn',NULL,'Tesfamichael', '(123) 4567890', 'kat@work.email','kat@personal.email','George Mason University', 'PhD','Computer Science'),
(2,'John','A','Smith','(234) 5678901', 'john.smith@work.edu', 'jsmith@gmail.com','University of Virginia','BS', 'Early Education'),
(3,'Emily', NULL,'Clark','(345) 6789012', 'eclark@work.edu', 'emily.clark@gmail.com','George Mason University','MS', 'Mathematics');
SELECT * FROM TEACHER_AT;

INSERT INTO CLASS_AT VALUES
('G1', 'foxes','GF',101,'(777) 7890123','North wing, near front door', 20),
('P1', 'monkeys', 'PM',202,'(999) 0123456','East wing, 2nd floor', 18),
('R2', 'turtles', 'RT',103,'(111) 1234567', 'West wing, 1st floor', 22);
SELECT * FROM CLASS_AT;

INSERT INTO ASSIGNMENT_AT VALUES
('G1', 1),
('P1', 2),
('R2', 3);
SELECT * FROM ASSIGNMENT_AT;

INSERT INTO STUDENT_AT VALUES
(1,'Alice', NULL,'Johnson', 'Ali','2015-08-15','123 Maple St','Fairfax',22030, 'Maple Street','G1'),
(2,'Bob','Michael','Williams',NULL,'2016-05-20','456 Oak Ave', 'Falls Church',22046, 'Oak Avenue','P1'),
(3,'Carol', 'Ann','Davis','Cara','2013-11-10','789 Pine Rd','Arlington', 22201,'Pine Road','R2');
SELECT * FROM STUDENT_AT;

INSERT INTO PARENT_AT VALUES
(1, 'Jane',   NULL, 'Johnson', '(111) 2223333', '(111) 4445555', '(111) 6667777', 'johnson@parent.com', 'Mother'),
(2, 'William','JR', 'Williams','(222) 3334444', '(222) 5556666', '(222) 7778888','williams@parent.com','Father'),
(3, 'Susan',  NULL, 'Davis', '(333) 4445555', '(333) 5556666', NULL, 'davis@parent.com', 'Mother');
SELECT * FROM PARENT_AT;

INSERT INTO RELATIONSHIP_AT VALUES
(1, 1),
(2, 2),
(3, 3);
SELECT * FROM RELATIONSHIP_AT;

INSERT INTO LUNCH_ITEM_AT VALUES
(1, 'Pizza ', 200),
(2, 'Sandwich',300),
(3, 'Salad', 50),
(4, 'Apple Juice', 100);
SELECT * FROM LUNCH_ITEM_AT;

INSERT INTO LUNCH_ORDER_AT VALUES
(1, 2, '2025-05-01', 1),
(2, 2, '2025-05-03', 2),
(3, 1, '2025-05-05', 3);
SELECT * FROM LUNCH_ORDER_AT;

INSERT INTO ORDER_ITEM_AT VALUES
(1, 1),
(1, 4),
(2, 2),
(2, 4),
(3, 3);
SELECT * FROM ORDER_ITEM_AT;

-- Task 5 - Query the data ADONAY TESFAMICHAEL
-- List all students names (in a column named 'Student') in alphabetical order, with the age level (in a column named 'Level'), color and directions of the class and the name of the teacher (in a column named 'Teacher').
SELECT CONCAT_WS(' ',STUDENT_AT.FIRST_NAME_AT, STUDENT_AT.MIDDLE_NAME_AT,STUDENT_AT.LAST_NAME_AT) AS Student,
  CLASS_AT.AGE_LEVEL_AT AS Level,
  CLASS_AT.COLOR_AT AS Color,
  CLASS_AT.DIRECTION_AT AS Direction,
  CONCAT_WS(' ',TEACHER_AT.FIRST_NAME_AT,TEACHER_AT.MIDDLE_NAME_AT,TEACHER_AT.LAST_NAME_AT) AS Teacher
FROM STUDENT_AT
JOIN CLASS_AT ON STUDENT_AT.CLASS_AT_CODE_AT = CLASS_AT.CODE_AT
JOIN ASSIGNMENT_AT ON CLASS_AT.CODE_AT = ASSIGNMENT_AT.CLASS_AT_CODE_AT
JOIN TEACHER_AT ON ASSIGNMENT_AT.TEACHER_AT_ID_AT = TEACHER_AT.ID_AT
ORDER BY Student ASC;
-- For each class level and color show all the student enrolled in alphabetical order per each class (i.e. you start with blue foxes and show all the students enrolled alphabetically, then you go to green foxes, and so on) and their zipcode. Use the following headers for the columns: Color, Level, Student Name, Zipcode
SELECT CLASS_AT.COLOR_AT AS Color,
CLASS_AT.AGE_LEVEL_AT AS Level,
CONCAT_WS(' ',STUDENT_AT.FIRST_NAME_AT, STUDENT_AT.MIDDLE_NAME_AT,STUDENT_AT.LAST_NAME_AT ) AS Student_Name,
STUDENT_AT.ZIPCODE_AT AS Zipcode 
FROM STUDENT_AT 
JOIN CLASS_AT ON STUDENT_AT.CLASS_AT_CODE_AT = CLASS_AT.CODE_AT
ORDER BY Color ASC,
Level ASC, 
Student_Name ASC;
-- For each parent (caretaker) in alphabetical order (show name and work phone), list all the students enrolled (show name, class level and color)
SELECT CONCAT_WS(' ',PARENT_AT.FIRST_NAME_AT, PARENT_AT.MIDDLE_NAME_AT,PARENT_AT.LAST_NAME_AT) AS Parent,
  PARENT_AT.WORK_PHONE_AT AS WorkPhone,
  CONCAT_WS(' ',STUDENT_AT.FIRST_NAME_AT, STUDENT_AT.MIDDLE_NAME_AT, STUDENT_AT.LAST_NAME_AT) AS Student,
  CLASS_AT.AGE_LEVEL_AT AS Level,
  CLASS_AT.COLOR_AT AS Color
FROM PARENT_AT 
JOIN RELATIONSHIP_AT ON PARENT_AT.ID_AT = RELATIONSHIP_AT.PARENT_AT_ID_AT
JOIN STUDENT_AT ON RELATIONSHIP_AT.STUDENT_AT_ID_AT  = STUDENT_AT.ID_AT
JOIN CLASS_AT ON STUDENT_AT.CLASS_AT_CODE_AT  = CLASS_AT.CODE_AT
ORDER BY Parent ASC, Student ASC;
-- For each parent (show name in alphabetical order) list all the teachers (show name in alphabetical order per parent) and their children(students) (show names in alphabetical order per teacher). Use columns headers: parent, teacher, student
SELECT CONCAT_WS(' ',PARENT_AT.FIRST_NAME_AT, PARENT_AT.MIDDLE_NAME_AT, PARENT_AT.LAST_NAME_AT)  AS parent,
  CONCAT_WS(' ',TEACHER_AT.FIRST_NAME_AT, TEACHER_AT.MIDDLE_NAME_AT,TEACHER_AT.LAST_NAME_AT)  AS teacher,
  CONCAT_WS(' ',STUDENT_AT.FIRST_NAME_AT, STUDENT_AT.MIDDLE_NAME_AT, STUDENT_AT.LAST_NAME_AT)  AS student
FROM PARENT_AT 
JOIN RELATIONSHIP_AT ON PARENT_AT.ID_AT = RELATIONSHIP_AT.PARENT_AT_ID_AT
JOIN STUDENT_AT ON RELATIONSHIP_AT.STUDENT_AT_ID_AT = STUDENT_AT.ID_AT
JOIN CLASS_AT ON STUDENT_AT.CLASS_AT_CODE_AT = CLASS_AT.CODE_AT
JOIN ASSIGNMENT_AT ON CLASS_AT.CODE_AT = ASSIGNMENT_AT.CLASS_AT_CODE_AT
JOIN TEACHER_AT ON ASSIGNMENT_AT.TEACHER_AT_ID_AT = TEACHER_AT.ID_AT
ORDER BY parent ASC, teacher ASC, student ASC;

